CREATE SCHEMA FAMILY_TREE_MAKER;

SET SCHEMA FAMILY_TREE_MAKER;

CREATE TABLE FAMILY_TREES (
    ID INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    NAME VARCHAR(50) NOT NULL
);

CREATE TABLE FAMILY_TREE_MEMBERS (
    ID INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    FAMILY_TREE_ID INT NOT NULL,
    SEX INT NOT NULL,
    FIRST_NAME VARCHAR(50) NOT NULL,
    MIDDLE_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE DB_VERSION (
	VERSION INT NOT NULL
);
INSERT INTO DB_VERSION VALUES (1);
